# Generated by Django 4.0.2 on 2022-02-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_image_alter_review_review_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_at',
        ),
    ]
